apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: sealed-secrets-backup

resources:
  - namespace.yaml
  - rbac.yaml
  - configmap.yaml
  - label-check-deployment.yaml
  - cronjob.yaml
